/* Generated by tools/convert.js — edit freely, it is not regenerated. */
window.KA_CONFIG = {
  title: "Zenith",

  /* Detected from size(600, 600) call. */
  width: 600,
  height: 600,

  /* Khan Academy audio. Files go in sounds/<name>.mp3 ; leave enabled and
     the game simply stays silent when a file is missing. */
  sound: true
};
