/* Zenith — generated by tools/convert.js
 * Do not edit by hand. Re-run the converter against the Khan Academy
 * source instead, so the game logic stays byte-identical.
 *
 * Edits applied: none
 */

/**
 * Zenith
 * littlewhinging x Corin Fist
 * 
 * Date started: 9/1/21
 * Date finished: 10/5/21
 * Date released: 10/5/21
 * 
 * @References {
 *  Background Graphic RI: https://www.vectorstock.com/royalty-free-vector/flat-simple-landscape-background-vector-10035182
 * }
 * @log {
 * 9/1/21: Started work on the program, with background menu graphic
 * 9/2/21: Got Corin Fist onboard! Starting platformer physics, Corin Fist starting graphics.
 * 9/3/21: Almost finished platformer physics. Corin Fist finished with graphics.
 * 9/4/21: Got physics, adding blocks.
 * }
 * @SUBSCRIBE to littlewhinging: https://www.khanacademy.org/computer-programming/littlewhingings-sub-page/6637078393733120
 * @SUBSCRIBE to Corin Fist: https://www.khanacademy.org/computer-programming/homepage/5781861949784064
*/

var leader = [
    ["LittleWhining",13],
    ["Hypar",2],
    ["somebody",3],
    ["Peter B.",34],
    ["Valenzuela, Riley",8],
    ["Cubic Coding",43],
    ["judahmuzik",23],
    ["RJR",10],
    ["Fire Hawk 360",67],
    ["striker",111],
    ["Roronoa_Zoro",14],
    ["S2MM13",0],
    ["Aidan Pincin",14]
];


var sortArr = function(arr, ind) {
    for (var i = 0; i < arr.length - 1; i++) {
        for (var j = i + 1; j < arr.length; j++) {
            if (arr[j][ind] <= arr[i][ind]) {
                var temp = arr[j];
                arr[j] = arr[i];
                arr[i] = temp;
                if (arr[j][0] === arr[i][0]) {
                    arr.splice(i, 1);
                }
            }
        }
    }
};
sortArr(leader, 1);


/** Program Setup **/
//{
    //jshint ignore: start
    var scene = "logo";
    size(600, 600, P2D);
    noStroke();
    randomSeed(300);
    strokeCap(SQUARE);
    textAlign(CENTER, CENTER);
    var f = createFont("Trebuchet MS");
    var fb = createFont("Trebuchet MS Bold");
    var fi = createFont("Trebuchet MS Italics");
    var fbi = createFont("Trebuchet MS Bold Italics");
//}

/** User Interactivity (UI) **/
//{    
    var clicked = [];
    var keys = [];
    var typed = [];
    var Button = function(x, y, w, h, msg){
        this.x = x;
        this.y = y;
        this.w = w;
        this.w2 = w;
        this.h = h;
        this.msg = msg;
    };
    Button.prototype.update = function(){
        this.inside = mouseX > this.x - this.w/2 && mouseX < this.x + this.w/2 && mouseY > this.y - this.h/2 && mouseY < this.y+this.h/2;
        this.triggered = this.inside && clicked[LEFT];
    };
    Button.prototype.animate = function(){
        if (this.inside){
            this.w = lerp(this.w, this.w2*1.2, 0.1);
        }
        else {
            this.w = lerp(this.w, this.w2, 0.1);
        }
    };
    Button.prototype.draw = function() {
        rectMode(CENTER);
        textAlign(CENTER, CENTER);
        noFill();
        stroke(255);
        strokeWeight(this.w/40);
        pushMatrix();
        translate(this.x, this.y);
        scale(this.w/this.w2);
        rect(0, 0, this.w, this.h);
        fill(255);
        textFont(createFont("Trebuchet MS"), 30);
        text(this.msg, 0, 0);
        popMatrix();
        rectMode(CORNER);
    };
    Button.prototype.pack = function(){
        this.update();
        this.draw();
        this.animate();
    };
    var backBtn = new Button(150, 533, 200, 100, "Back");
//}

/** Graphics **/
//{
    var yeti = (function(){
        background(0, 0);
        pushMatrix();
            translate(100,100);
            fill(235, 235, 235);
            strokeWeight(2);
            stroke(36, 31, 36);
            rect(-6,-4,72,70,34);
            
            noStroke();
            fill(180, 214, 250);
            ellipse(31,47,61,37);
            
            
            
            for(var i = 0;i<5;i++){
                fill(43, 36, 36);
                arc(3+i*10,3,23,39,-100+i*15,35);
                fill(255, 255, 255);
                arc(4+i*10,6,17,41,-100+i*15,35);        
            }
            
            fill(235, 235, 235);  
            ellipse(17,39,36,37);
            ellipse(32,44,10,37);
            ellipse(44,44,22,31);    
            ellipse(50,37,22,31);   
            ellipse(29,9,52,31);      
            
            
            
            noStroke();
            fill(27, 35, 41);
            ellipse(30,28,63,28);
            ellipse(15,20,36,23);
            ellipse(44,19,36,23);
            ellipse(15,25,36,23);
            ellipse(47,23,36,23);
        
            
            fill(105, 192, 250);
            arc(30,22,63,33,0,180);
            arc(17,22,36,23,180,360);
            arc(44,22,36,23,180,360);
        
            fill(93, 173, 222);
            arc(30,30,49,16,0,180);
            arc(37,30,49,-3,0,180);
            arc(25,30,49,-3,0,180);  
            
            fill(30,30,30);
            ellipse(15,22,15,15);
            ellipse(45,22,15,15);
            
            fill(240, 136, 136);
            ellipse(17,20,4,4);
            ellipse(47,20,4,4);    
            
            
            
            stroke(28, 25, 25);
            noFill();
            arc(30,35,18,10,-180,0);
            
            strokeWeight(1);
            fill(240, 240, 240);
            triangle(39,34,35,30,40,28);
            triangle(22,34,27,30,19,29);
            
            
        
            
        popMatrix();
        return get(90, 90, 80, 80);
    })();
    var smortyeti = (function(){
        background(0, 0);
        pushMatrix();
            translate(100,100);
            fill(235, 235, 235);
            strokeWeight(2);
            stroke(36, 31, 36);
            rect(-6,-4,72,70,34);
            
            noStroke();
            fill(9, 88, 161);
            ellipse(31,47,61,37);
            
            
            
            for(var i = 0;i<5;i++){
                fill(43, 36, 36);
                arc(3+i*10,3,23,39,-100+i*15,35);
                fill(255, 255, 255);
                arc(4+i*10,6,17,41,-100+i*15,35);        
            }
            
            fill(235, 235, 235);  
            ellipse(17,39,36,37);
            ellipse(32,44,10,37);
            ellipse(44,44,22,31);    
            ellipse(50,37,22,31);   
            ellipse(29,9,52,31);      
            
            
            
            noStroke();
            fill(27, 35, 41);
            ellipse(30,28,63,28);
            ellipse(15,20,36,23);
            ellipse(44,19,36,23);
            ellipse(15,25,36,23);
            ellipse(47,23,36,23);
        
            
            fill(11, 94, 150);
            arc(30,22,63,33,0,180);
            arc(17,22,36,23,180,360);
            arc(44,22,36,23,180,360);
        
            fill(11, 94, 150);
            arc(30,30,49,16,0,180);
            arc(37,30,49,-3,0,180);
            arc(25,30,49,-3,0,180);  
            
            fill(30,30,30);
            ellipse(15,22,15,15);
            ellipse(45,22,15,15);
            
            fill(240, 136, 136);
            ellipse(17,20,4,4);
            ellipse(47,20,4,4);    
            
            
            
            stroke(28, 25, 25);
            noFill();
            arc(30,35,18,10,-180,0);
            
            strokeWeight(1);
            fill(240, 240, 240);
            triangle(39,34,35,30,40,28);
            triangle(22,34,27,30,19,29);
            
            
        
            
        popMatrix();
        return get(90, 90, 80, 80);
    })();
    var bkgd = (function(){
        background(173, 154, 155);
        var col1 = color(104, 150, 150);
        var col2 = color(173, 154, 155);
        var dimY = 300;
        strokeWeight(1);
        for (var i = 0;i<dimY;i++){
            stroke(lerpColor(col1, col2, i/dimY));
            line(0, i, 600, i);
        }
        stroke(255, 150);
        strokeWeight(3);
        for (var i = 0;i<40;i++){
            point(random(0, 600), random(0, 300));
        }
        return get();
    })();
    var mountains = (function(){
        background(0, 0);
        noStroke();
        fill(167, 183, 173);
        triangle(488, 156, 0, 366, 872, 444);
        fill(81, 183, 185);
        triangle(300, 156, 0, 366, 727, 444);
        fill(63, 131, 168);
        triangle(0, 221, 0, 600, 600, 459);
        fill(50, 40, 85);
        triangle(600, 300, 200, 600, 600, 600);
        quad(0, 435, 0, 600, 30, 647, 121, 342);
        fill(62, 77, 118);
        quad(420, 435, 201, 600, 29, 647, 120, 342);
        return get();
    })();
    var sign = (function(){
        background(255, 0);
        fill(107, 69, 49);
        rect(0, 0, 50, 50);
        for(var y = 0;y<50/4;y++){
            for(var i = 0;i<50/4;i++){
                
                noStroke();
                fill(0, 0, 0,random(20,50));
                rect(i*4,y*4,4,4);
        }}              
        
        fill(255);
        rect(4, 4, 42, 42,10);
        fill(0);
        textFont(f, 2);
        text("Blah blah blah blah blah blah\nBlah blah blah blah blah blah\nare you actually reading the code\nbruh stop and actually play\nthe game lol that's better\nbecause corin is epic and made\nepic stuff for the game unlike me\nhehe well enjoy the code ig?\nif you're actually gonna read it\nI can't believe I'm actually\ndoing this for a filler message", 25, 25);
        return get();
    })();
    var mountPeak = (function(){
        background(0, 0);
        stroke(0);
        strokeWeight(6);
        line(73,241,123,73);
        line(123,73,231,237);
        line(107,118,107,118);
        line(110,115,124,126);
        line(124,126,135,117);
        line(135,117,161,130);
        line(155,120,198,45);
        line(198,45,328,237);
        line(179,80,192,93);
        line(192,93,206,82);
        line(206,82,228,91);
        line(14,224,69,68);
        line(69,68,103,139);
        line(56,103,65,111);
        line(65,111,82,99);
        noStroke();
        return get(0, 0, 600, 600);
    })();
    var T1 = (function(){
        background(0, 0);
        stroke(85, 45, 133);
        strokeWeight(3);
        for (var i = 0;i<360;i+=30){
            pushMatrix();
            translate(25, 25);
            rotate(i);
            line(0, 0, 0, -25);
            popMatrix();
        }
        filter(BLUR, 1.5);
        return get(0, 0, 50, 50);
    })();
    var T2 = (function(){
        background(0, 0);
        stroke(45, 94, 133);
        strokeWeight(3);
        for (var i = 0;i<360;i+=30){
            pushMatrix();
            translate(25, 25);
            rotate(i);
            line(0, 0, 0, -25);
            popMatrix();
        }
        filter(BLUR, 1.5);
        return get(0, 0, 50, 50);
    })(); 
    var Trampoline = (function(){
        background(0, 0);
        stroke(200);
        strokeWeight(7);
        line(6, 4, 38, 41);
        line(47, 1, 11, 41);
        fill(224, 102, 237);
        noStroke();
        rect(0, 0, 50, 10);
        fill(200);
        rect(0, 40, 50, 10);
        return get(0, 0, 50, 50);
    })();
    var Cave = (function(){
        background(77, 68, 54);
        noStroke();
        for (var i = 0;i<600;i+=60){
            fill(43, 37, 33);
            triangle(i, 0, i+random(25, 40), 0, i + random(5, 50), random(142, 172));
            fill(64, 59, 56);
            triangle(i, 0, i+random(25, 40), 0, i + random(5, 50), random(120, 150));
        }
        fill(61, 59, 57);
        beginShape();
        vertex(0, 600);
        vertex(600, 600);
        vertex(600, 500);
        vertex(501, 518);
        vertex(466, 497);
        vertex(289, 518);
        vertex(185, 499);
        vertex(100, 531);
        vertex(55, 531);
        vertex(0, 505);
        endShape(CLOSE);
        
        fill(43, 37, 33);
        pushMatrix();
        translate(0, 30);
        beginShape();
        vertex(0, 600);
        vertex(600, 600);
        vertex(600, 500);
        vertex(501, 518);
        vertex(466, 497);
        vertex(208, 518);
        vertex(184, 499);
        vertex(99, 511);
        vertex(55, 531);
        vertex(0, 505);
        endShape(CLOSE);
        popMatrix();
        return get(0, 0, 600, 600);
    })();
    var texture = (function(){
        background(0,0);
        for(var y = 0;y<50/4;y++){
            for(var i = 0;i<50/4;i++){
                
                noStroke();
                fill(0, 0, 0,random(20,50));
                rect(i*4,y*4,4,4);
        }}        
        return get(0,0,50,50);
    })();
    
//}

/** Game Setup **/
//{
    var curLevel = 0;
    var deaths = 0;
    
    /** Collision Detection **/
    //{
        var col = function(obj1, obj2){
            return obj1.x + obj1.w > obj2.x && obj1.x < obj2.x + obj2.w && obj1.y + obj1.h > obj2.y && obj1.y < obj2.y + obj2.h;
        };
    //}
    
    /** Death **/
    //{
        var die = function(func, move){
            
            if (move){
                curLevel++;
            }
            else {
                deaths++;
            }
            func();
        };
    //}
    
    /** Player **/
    //{
    function cuteEyes(x,y,s,r,fade){
        pushMatrix();
            translate(x,y);
            scale(s);
            rotate(r);
            
            
            fill(0,0,0);
            noStroke();
            ellipse(0,0,100,100);
    
            fill(255, 255, 255);
            ellipse(-17,-11,50,50);
            ellipse(26,-15,15,15);
            ellipse(-13,32,15,15);
             rotate(-r);       
            rotate(+0);
            fill(255, 232, 229, fade);
            ellipse(-6,57,101,29);
            
        popMatrix();
        
    
    }
    function Player(x,y){
        this.x = x;
        this.y = y;
        this.h = 50;
        this.w = 40;
        
    
        
        this.colw = 40;
        this.colx = 0;
        
        //Current positions
        this.quads = [0,0,this.w,0,this.w,this.h,0,this.h,this.w-8,18,7,18,255,0];
        this.position = "stop";
        this.pospd = 0.07;
        
        //The speeds
        this.maxSpd = 1000;
        this.acc = 0.3;
        this.speed = 0;
        this.decel = 0.9;
        
        //gravity
        this.grav = 0.4;
        this.maxfall = 20;
        this.fallspd = 0;
        this.ajump = false;
        this.landTimer = 0;
         
        this.timeout = 0;//timing to switch back to the stop position 
        this.health = 100; //Health
                    
        //Order is left quad,right quad, bottom left, bottom right, eyes,eyes2,eyescutefade, mouth
        this.jumpA = [0,-3,this.w-15,-3,this.w+-8,this.h,-9,this.h,this.w-15,30,0,30,0,-7];
        this.moveLA = [-24,-5,this.w-32,-5,this.w+-1,this.h,1,this.h,-10,6,-10,6,0,-20];
        this.moveRA = [24,-5,this.w+7,-5,this.w+-1,this.h,1,this.h,this.w-3,6,this.w-3,6,0,15];
        this.fallA = [-2,-9,this.w+2,-9,this.w+-5,this.h,5,this.h,this.w-8,0,8,0,255,0];
        this.land = [0,20,this.w,25,this.w+20,this.h,-20,this.h,this.w-5,32,3,31,255,0];
        this.stop = [0,0,this.w,0,this.w,this.h,0,this.h,this.w-8,18,7,18,255,0];
        this.currentA = [0,0,this.w,0,this.w,this.h,0,this.h,0,0,0,0];
    }
    Player.prototype.pos_trans = function(){
        
        //Switching the "Going to be" position
        switch(this.position){
            case "left":
                
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.moveLA[i];
                }     
                this.pospd = 0.07;
            break;
            
            case "right":
                
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.moveRA[i];
                }          
                this.pospd = 0.07;
            break;
            
            case "stop":
                
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.stop[i];
                }          
                this.pospd = 0.07;
            break;        
            case "land":
                
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.land[i];
                }          
                this.pospd = this.landTimer/5;
            break;         
            case "fall":
                this.pospd = 0.1;
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.fallA[i];
                }          
                
            break;   
            case "jump":
                this.pospd = 0.07;
                for(var i = 0;i<14;i++){
                    this.currentA[i] =this.jumpA[i];
                }          
                
            break;  
        }
    };
    Player.prototype.update = function(){
       
        //Updating the figure of the cube
    
        this.timeout*=0.3;    
        if(this.timeout<=0.1&&this.ajump === true&&this.landTimer<0.2){
            this.position = "stop";
        }
        
         if(this.ajump === true&&this.landTimer>0.1&&this.fallspd<0.5){
            this.landTimer*=0.95;
            this.position = "land";
        }
        
        this.landTimer = constrain(this.landTimer,0.1,1.5);
        
        fill(255,0,0);
    //    text(this.fallspd,10,10);
      //  text(this.landTimer,100,10);
    };
    Player.prototype.moveX = function(){
        //--------------- X AXIS -----------------//
        
        //Moving the x axis with the speed
        this.x += this.speed;
        
        //Moving left and right
        if(keys[65] || keys[LEFT]){
            this.position = "left";
            this.timeout = 1;
            if (this.speed > -5){
                this.speed -= this.acc;
            }
        } 
        
        else if(keys[68] || keys[RIGHT]){
            this.position = "right";
            this.timeout = 1;
            if (this.speed < 5){
                this.speed += this.acc;
            }
        }
        else {
            this.speed *= this.decel;
        }    
    };
    Player.prototype.moveY = function(){
       //-----------Y AXIS----------//
        
        this.y += this.fallspd; //making the player fall
        
        this.fallspd +=this.grav; //applying world gravity
        
       this.fallspd = constrain(this.fallspd,-this.maxfall,this.maxfall);
        
        if(this.fallspd>1){
                this.position = "fall";
                this.landTimer+=0.05;
        }   
    
        
        if(keys[87] && this.ajump || keys[UP] && this.ajump){
            this.position = "jump";
            this.fallspd = -this.maxfall/1.6;
            this.ajump = false;
        }    
    };
    Player.prototype.draw = function(){
        this.update();
        this.pos_trans();
        
        var q = this.quads;
        
        //Drawing the looks 
        pushMatrix();
            translate(this.x-this.quads[0]/2,this.y);
            fill(0, 229, 245);        
            noStroke();
            quad(q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7]);
            
            cuteEyes(q[8],q[9],0.11,0,q[12]);
            cuteEyes(q[10],q[11],0.11,90,q[12]);
    
            fill(0,0,0);
            arc(20+q[13],this.h/2,9,10,0,180);  
    
    
            fill(255, 255, 255,100);
         //   rect(this.quads[0],q[1],this.quads[2]-this.quads[0],this.h-q[1]);
            
            fill(0,0,0);
         //   text(this.colx,0,0);
          //  text(this.x,0,20);
          //  text(this.quads[0],0,40);
        //    this.fallspd+=this.grav;
        popMatrix();
        
        //Collisions modified
        this.colw = this.quads[2]-this.quads[0];
        this.colx = this.x+this.quads[0];
        
        //Lerping the players body to the position specified
        for(var i = 0;i<14;i++){
            this.quads[i] =lerp(this.quads[i],this.currentA[i],this.pospd);
        }
      
    };
    var player;
    //}
    
    /** Block **/
    //{
        var Block = function(x, y, w, h, t){
            this.x = x; //X position
            this.y = y; //Y position
            this.w = w; //Width
            this.h = h; //Height
            this.t = t; //Type
            curLevel > 19  && curLevel < 25? this.color = color(117, 113, 108) : this.color = color(150, 110, 140);
        };
        Block.prototype.draw = function() {
            switch (this.t){
                case 0:
                    fill(this.color);
                    stroke(this.color);
                    strokeWeight(1);
                    rect(this.x, this.y, this.w, this.h);
                    image(texture,this.x,this.y);

                    
                break;
                case 1:
                    fill(209, 244, 255);
                    stroke(209, 244, 255);
                    strokeWeight(1);
                    rect(this.x, this.y, this.w, this.h);
                    fill(229, 249, 255);
                    noStroke();
                    quad(this.x + 20, this.y, this.x + 10, this.y + this.h, this.x + 30, this.y + this.h, this.x + 40, this.y);
                    noStroke();
                break;
            }
        };
        Block.prototype.collideX = function(obj1){
            switch (this.t) {
                case 0:
                    obj1.rightC = false;
                    obj1.leftC = false;
                    if (col(this, obj1)){
                        if (obj1.x < this.x) {
                            obj1.x = this.x - obj1.w;
                            obj1.rightC = true;
                        } 
                        else if (obj1.x>this.x){
                            obj1.x = this.x + this.w;
                            obj1.leftC = true;
                        }
                    }
                break;
                case 1:
                    if (col(this, obj1)){
                        
                        if (obj1.x < this.x) {
                            obj1.x = this.x - obj1.w;
                        } 
                        else if (obj1.x>this.x){
                            obj1.x = this.x + this.w;
                        }
                        
                    }
            }
        };
        Block.prototype.collideY = function(obj1){
            switch (this.t){
                case 0:
                    if (col(this, obj1)) {
                        
                        if (obj1.y < this.y) {
                            obj1.ajump = true;
                            obj1.y = this.y - obj1.h;
                            obj1.fallspd = 0;
                        } 
                        else if (obj1.y > this.y){
                            obj1.y = this.y + this.h;
                            obj1.ajump = false;
                            obj1.fallspd *= -0.5;
                        }
                    }
                break;
                case 1:
                    if (col(this, obj1)) {
                        obj1.speed *= 1.03;
                        if (obj1.y < this.y) {
                            obj1.ajump = true;
                            obj1.y = this.y - obj1.h;
                            obj1.fallspd = 0;
                        } 
                        else if (obj1.y > this.y){
                            obj1.y = this.y + this.h;
                            obj1.ajump = false;
                            obj1.fallspd *= -0.5;
                        }
                    }
                break;
            }
        };
    //}
    
    /** Obstacle **/
    //{
        var Obs = function(x, y, type){
            this.x = x;
            this.y = y;
            this.w = 50;
            this.h = 50;
            this.yetiX = x;
            this.yetiY = y;
            this.signY = -600;
            this.t = type;
        };
        Obs.prototype.draw = function(){
            switch (this.t){
                case 0:
                    noStroke();
                    fill(150, 150, 150);
                    triangle(this.x+25/2, this.y, this.x, this.y + 50, this.x + 25, this.y + 50);
                    triangle(this.x + 25, this.y + 50, this.x + 25+25/2, this.y, this.x + 50, this.y + 50);
                break;
                case 1:
                    stroke(19, 0, 128);
                    noFill();
                    strokeWeight(5);
                    ellipse(this.x + this.w/2, this.y + this.h/2 - 10 + sin(frameCount*2)*5, 40, 40);
                    stroke(0, 102, 133);
                    ellipse(this.x + this.w/2, this.y + this.h/2 - 10 + sin(frameCount*2)*5, sin(frameCount*4)*20, 20);
                    ellipse(this.x + this.w/2, this.y + this.h/2 - 10 + sin(frameCount*2)*5, 20, sin(frameCount*3)*20);
                    ellipse(this.x + this.w/2, this.y + this.h/2 - 10 + sin(frameCount*2)*5, sin(frameCount*3.5)*20, sin(frameCount*3.5)*20);
                    ellipse(this.x + this.w/2, this.y + this.h/2 - 10 + sin(frameCount*2)*5, 20, 20);
                    fill(0, 100);
                    noStroke();
                    ellipse(this.x + this.w/2, this.y + this.h, -sin(frameCount*2)*5 + 30, 5);
                break;
                case 2:
                    image(sign, this.x, this.y);
                break;
                case 3:
                    imageMode(CENTER);
                    pushMatrix();
                    translate(this.x + 25, this.y + 25);
                    rotate(frameCount*3);
                    image(T1, 0, 0);
                    popMatrix();
                    imageMode(CORNER);
                break;
                case 4:
                    imageMode(CENTER);
                    pushMatrix();
                    translate(this.x + 25, this.y + 25);
                    rotate(frameCount*3);
                    image(T2, 0, 0);
                    popMatrix();
                    imageMode(CORNER);
                break;
                case 5:
                    image(Trampoline, this.x, this.y);
                break;
                case 6:
                    image(yeti, this.x, this.y, 50, 52);
                break;
                case 7:
                     fill(0);
                     rect(this.x, this.y, 50, 50);
                break;
                    
            }
        };
    //}
    
    /** Smort Yeti **/
    //{
        var Yeti = function(x, y){
            //Coordinates
            this.x = x;
            this.y = y;
            
            //Dimensions
            this.w = 50;
            this.h = 50;
            
            //Move
            this.speed = 0;
            this.fallspd = 0;
            this.grav = 0.4;
            this.ajump = false;
            this.health = 100;
        };
        Yeti.prototype.draw = function() {
            image(smortyeti, this.x, this.y, 53, 53);
        };
        Yeti.prototype.moveX = function(obj){
            if (obj.x < this.x){
                this.speed = -2;
            }
            else if (obj.x > this.x){
                this.speed = 2;
            }
            else {
                this.speed *= 0.9;
            }
            if (col(this, obj)){
                obj.health--;
            }
            this.x += this.speed;
        };
        Yeti.prototype.moveY = function(obj){
            if (player.y < this.y && this.ajump){
                this.fallspd = -8;
                this.ajump = false;
                this.grav = 0.4;
            }
            this.y += this.fallspd;
            this.fallspd += this.grav;
        };
        var yetis = [];
    //}
    
    /** Level Bitmaps **/
    //{
        var maps = [
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "B@  S   PB            ",
                    "BBBBBBBBBB            ",
                ],
                message: "Welcome to the game!\nGet to the portal to continue."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "       P              ",
                    "       BBBB     B     ",
                    "                      ",
                    "                    B ",
                    "                      ",
                    "                      ",
                    "           B        B ",
                    "                      ",
                    "        B      B      ",
                    "    B                 ",
                    "                      ",
                    "                      ",
                    "B                     ",
                    "                      ",
                    "     B                ",
                    "                      ",
                    "                      ",
                    "     B                ",
                    "                      ",
                    "B@  S                 ",
                    "BBBBBB                ",
                ],
                message: "Who's up for some par core?\nFall and you die.\nBy the way, did you just\nsee that green thing\non the left go up?\nThat's your progress to the zenith.\nYour goal is to get all the way up there."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "B@  S       ^^^^^^^  P",
                    "BBBBBBBBB^^^BBBBBBBBBB",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "Ouch. Spikes."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "       B              ",
                    "       B              ",
                    "       B              ",
                    "       B              ",
                    "B@  S TB&            P",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "This is a teleporter.\nThe purple one teleports you.\nNo going back."
            },
            {
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "       ^              ",
                    "       B              ",
                    "       B              ",
                    "       B              ",
                    "       B              ",
                    "       B              ",
                    "B@  S TB&             ",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                    "                      ",
                    "                      ",
                    "  ^^^^^   P           ",
                    "BBBBBBBBBBBB          ",
                    "                      ",
                ],
                message: "Press R to restart."
            },
            {
                map: [
                    "                      ",
                    "                      ",
                    "           P          ",
                    "          BB          ",
                    "                      ",
                    "      &^^             ",
                    "      BBBBB           ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "               B      ",
                    "               B      ",
                    "               B      ",
                    "               BT     ",
                    "               BBBB   ",
                    "                      ",
                    "                      ",
                    "                     B",
                    "        S           BB",
                    "    BBBBBB        BBBB",
                    "                      ",
                    "@                     ",
                    "BBBB                  ",
                ],
                message: "Did you know?\nYou can jump after walking\noff a block."
            },
            {
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "         T            ",
                    "         B            ",
                    "        B             ",
                    "       B      B      P",
                    "      B        BBBBBBBB",
                    "     B         B    & B",
                    "@ S B          B      B",
                    "BBBB           B^^^^^^B",
                    "               BBBBBBBB",
                ],
                message: "Big brain time."
            },
            {
                map: [
                    "          B       T   ",
                    "          B       B   ",
                    "          B           ",
                    "          B           ",
                    "@  S      BB          ",
                    "BBBBBBB   B           ",
                    "B     B  ^B      B    ",
                    "BP    B  BB           ",
                    "BB    B^  B           ",
                    "B     BB  B          B",
                    "B     B  ^B^^^^^      ",
                    "B    BB  BBBBBBBB     ",
                    "B     B   B           ",
                    "B     B^  B           ",
                    "B     BB  B        B  ",
                    "BB    B   B           ",
                    "B     B   B     B     ",
                    "B     B^^ B           ",
                    "B    BBBB BB          ",
                    "B     B   B           ",
                    "B     B   B    ^^^^^^^",
                    "B     B   BB   BBBBBBB",
                    "B    BB ^^B           ",
                    "B     B BBB           ",
                    "B     B   BB          ",
                    "B    &B      ^^^^^^^^ ",
                    "B^^^^BBBBBBBBBBBBBBBBBB",
                    "BBBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "So close, but also so far away."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "B@  S               PB",
                    "BBBBBIIIIIIIIIBBBBBBBB",
                ],
                message: "It's getting cold up here.\nI wonder what that ice does?"
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "        &  ^^^^   P   ",
                    "        BIIIIIIIIIB   ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                     T",
                    "                      ",
                    "B@ S                ^B",
                    "BBBBBIIIIIIIIIIIIIIBBB",
                ],
                message: "Wheeee"
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "B@ S                 T",
                    "BBBBBIIIIIIIIIII   BBB",
                    "               B   B  ",
                    "               B   B  ",
                    "               B   B  ",
                    "               B   B  ",
                    "               B   B  ",
                    "    &          B   B  ",
                    "               B  PB  ",
                    "               BBBBB  ",
                ],
                message: "Wheeee 2.0"
            },
            {  
                map: [
                    "                      ",
                    "          P           ",
                    "         BB           ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "  3                   ",
                    "                      ",
                    "         BB           ",
                    "         B            ",
                    "         B            ",
                    "         BB           ",
                    "                      ",
                    " ^^^^                 ",
                    " BBBB         B       ",
                    "                      ",
                    "         B            ",
                    "@  S                  ",
                    "BBBBBBB^^^^^^^^^^^^^^^",
                    "BBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "Trampolines are like spikes,\nexcept less deadly."
            },
            {  
                map: [
                    "   BBBBBBBB           ",
                    "   B   &  B           ",
                    "   B      B           ",
                    "   B^^^^^^B           ",
                    "   BBBBBBBB           ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "     T  T  T  T  T  T ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "@  S 3  3  3  3  3  3P",
                    "BBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "Like all things, trampolines are not\nalways your friends."
            },
            {  
                map: [
                    "       T     B         ",
                    "       B     B         ",
                    "             B&        ",
                    " B           BB        ",
                    "             B B      B",
                    "             B  B     B",
                    "             B   B^   B",
                    " B           B    B   B",
                    "             B     B  B",
                    "                   B^ B",
                    " B                 BB B",
                    "                   B  B",
                    "         B         B  B",
                    "                   B  B",
                    "                   B ^B",
                    "^^^^^^^^^          B BB",
                    "BBBBBBBBB     B    B  B",
                    "                   B  B",
                    "                   B^ B",
                    "       B           BB B",
                    "                   B  B",
                    "@  S   ^^^^^^^^^^^^B PB",
                    "BBBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "No amount of par core\nis too much :)"
            },
            {  
                map: [
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "@  S   Y              P",
                    "BBBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "Yetis? The brochure\ndid not mention that.\nIt's okay though, these guys\ncan't see you."
            },
            {  
                map: [
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "      B                ",
                    "      B                ",
                    "@  S  BU              P",
                    "BBBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "Smart yetis that follow you around?\nAlright, the brochure DEFINITELY\ndid not mention that."
            },
            {  
                map: [
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "       ^^^^^^^  P      ",
                    "   BBBBBBBBBBBBBB      ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "           U                      T",
                    "B          B                      B",
                    "B3  Y  Y & B           ",
                    "BBBBBBBBBBBB           ",
                    "                                  B",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                                    BBBB",
                    "@  S                   ",
                    "BBBBBIIIIIIIIIIIIIII   ",

                ],
                message: "Can you make the jump?"
            },
            {  
                map: [
                    "UUUUUUUUUUUUU @   S      ",
                    "BBBBBBBBBBBBBBBBBBBB    B     T",
                    "                              B",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "               B         ",
                    "               B         ",
                    "               B         ",
                    "               B         ",
                    "               B         ",
                    "               B         ",
                    "               B         ",
                    "&             PB         ",
                    "BBBBBBBBBBBBBBBB         ",
                ],
                message: "Even the \"smart\" yetis\nare kinda stupid."
            },
            {  
                map: [
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "               UUUU    ",
                    "                       ",
                    "                       ",
                    "   U U                 ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "       UUU             ",
                    "               UU      ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "           BBBB        ",
                    "@  S       BBBB       P",
                    "BBBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "It's raining yetis from\nout of the sky,\nyetis, no need to ask why."
            },
            {  
                map: [
                    "                       ",
                    "                       ",
                    "                   &  P",
                    "                   BBBB",
                    "T UUUUU                ",
                    "BBBBBBBB               ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "     U                 ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "  U                    ",
                    "             3    Y   ^",
                    "          BBBBBBBBBBBBB",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "                       ",
                    "BBBBB                  ",
                    "    B                  ",
                    "@  SB 3                ",
                    "BBBBBBBBBBBBBBBBBBBBBBB",

                ],
                message: "We must be getting near\na yeti cave or something."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "B@  S              U P",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "Huh, this is a nice cave.\nWatch out for the yetis."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "   BBBBBBBBBBBBBBBB   ",
                    "   B              B   ",
                    "   B&  UUUU      PB   ",
                    "   BBBBBBBBBBBBBBBB   ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "   U        U         ",
                    "                      ",
                    "      U                ",
                    "                       ",
                    "                      ",
                    "       U               ",
                    "                       ",
                    "                      ",
                    "                      ",
                    "BBBBBBBBBBB           ",
                    "B         B           ",
                    "B@ S     TB           ",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "That's a whole lot of yetis."
            },
            {  
                map: [
                    "                      ",
                    " @ S                  ",
                    "BBIIIIIIIIIIII IIIIIBB",
                    "BBBIIIIIIIIIII IIIIBBB",
                    "BBBBIIIIIIIIII IIIBBBB",
                    "BBBBBIIIIIIIII IIBBBBB",
                    "BBBBBBIIIIIIII IBBBBBB",
                    "BBBBBBBIIIIIII BBBBBBB",
                    "B                    B",
                    "B                    B",
                    "BP     YYY          UB",
                    "BBBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "It's the frozen lake of doom!"
            },
            {  
                map: [
                    "                     ",
                    " P              S   B",
                    "BBBBBBBBBBBBBBBBBBB B",
                    "B                   B",
                    "B  U          U     B",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B                   B",
                    "B   U         U    @B",
                    "BBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "Hey there,\nlong time no see :)"
            },
            {  
                map: [
                    "BP                   ",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B BBBBBBBBBBBBBBBBBBB",
                    "B                    ",
                    "B3                S@ ",
                    "BBBBBBBBBBBBBBBBBBBBB",
                ],
                message: "Here's a way out of the cave."
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "           S  P       ",
                    "          BBBBB       ",
                    "         B            ",
                    "        B             ",
                    "       B              ",
                    "      B               ",
                    "     B                ",
                    "    B                 ",
                    "   B                  ",
                    "  B                   ",
                    "@B                    ",
                    "BB                    ",
                ],
                message: "Almost there!"
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "              P       ",
                    "          BBBBB       ",
                    "         B            ",
                    "        B             ",
                    "       B              ",
                    "      B               ",
                    "     B                ",
                    "    B                 ",
                    "   B                  ",
                    "  B                   ",
                    "@B                    ",
                    "BB                    ",
                ],
                message: "Almost there!"
            },
            {  
                map: [
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "                      ",
                    "             @P       ",
                    "          BBBBB       ",
                    "         B            ",
                    "        B             ",
                    "       B              ",
                    "      B               ",
                    "     B                ",
                    "    B                 ",
                    "   B                  ",
                    "  B                   ",
                    " B                    ",
                    "BB                    ",
                ],
                message: "Almost there!"
            },
        ];
        var blocks = [];
        var block2s = [];
        var createLevel = function(){
            blocks[curLevel] = [];
            block2s[curLevel] = [];
            yetis[curLevel] = [];
            for (var i = 0;i<maps[curLevel].map.length;i++){
                for (var y = 0;y<maps[curLevel].map[i].length;y++){
                    var X = y*50;
                    var Y = i*50;
                    switch(maps[curLevel].map[i][y]){
                        case "B":
                            blocks[curLevel].push(new Block(X, Y, 50, 50, 0));
                        break;
                        case "@":
                            player = new Player(X,Y);
                        break;
                        case "^":
                            block2s[curLevel].push(new Obs(X, Y, 0));
                        break;
                        case "P":
                            block2s[curLevel].push(new Obs(X, Y, 1));
                        break;
                        case "S":
                            block2s[curLevel].push(new Obs(X, Y, 2));
                        break;
                        case "T":
                            block2s[curLevel].push(new Obs(X, Y, 3));
                        break;
                        case "&":
                            block2s[curLevel].push(new Obs(X, Y, 4));
                            maps[curLevel].teleportPlace = [X, Y];
                        break;
                        case "I":
                            blocks[curLevel].push(new Block(X, Y, 50, 50, 1));
                        break;
                        case "3":
                            block2s[curLevel].push(new Obs(X, Y, 5));
                        break;
                        case "Y":
                            block2s[curLevel].push(new Obs(X, Y, 6));
                        break;
                        case "U":
                            yetis[curLevel].push(new Yeti(X, Y));
                        break;
                        case "A":
                            block2s[curLevel].push(new Obs(X, Y, 7));
                        break;
                    }
                }
            }
        };
        Obs.prototype.collide = function(obj){
            if (this.t === 6){
                this.x = this.yetiX + sin(frameCount)*70;
            }
            if (this.t === 7){
                this.x = this.yetiX + sin(frameCount)*70;
                this.y = this.yetiY + sin(frameCount*4)*70;
            }
            if (col(this, obj)){
                switch (this.t){
                    case 0:
                        obj.health-=3;
                        obj.fallspd = -10;
                        obj.ajump = false;
                    break;
                    case 1:
                        die(createLevel, true);
                    break;
                    case 2:
                        this.signY = lerp(this.signY, 0, 0.1);
                    break;
                    case 3:
                        obj.x = maps[curLevel].teleportPlace[0];
                        obj.y = maps[curLevel].teleportPlace[1];
                    break;
                    case 5:
                        obj.fallspd = -20;
                    break;
                    case 6:
                        obj.health--;
                    case 7:
                        obj.health--;
                }
            }
            else {
                this.signY = lerp(this.signY, -600, 0.1);
            }
        };
        Obs.prototype.drawSign = function(){
            fill(0, 150);
            rect(0 - this.signY/2, this.signY, this.signY+600, this.signY+600);
            fill(255);
            textFont(fb, 30);
            pushMatrix();
            translate(300, this.signY + 300);
            scale(this.signY/600 + 1);
            text(maps[curLevel].message, 0, 0);
            popMatrix();
        };
    //}
    
    /** Snow **/
    //{
        var snowFall = (function(){
            var snow = [];
            var timerYay = 0;
            return function(){
                if (frameCount % 30 === 10){
                    snow.push({
                        x: random(0, 600),
                        y: -400,
                        xSpeed: random(-6, 6)
                    });
                }
                for (var i = 0;i<snow.length;i++){
                    fill(245, 240, 255);
                    noStroke();
                    ellipse(snow[i].x,snow[i].y, 7, 7);
                    snow[i].x-=snow[i].xSpeed;
                    snow[i].y+=10;
                    if (snow[i].x<-100){
                        if (snow.length<100){
                            snow[i].x = random(-100,500);
                            snow[i].y = -200;
                            snow[i].xSpeed = random(0.1,10);
                        }
                        else {
                            snow.splice(i, 1);
                        }
                    }
                    if (snow.length>200){
                        snow.splice(i, 200);
                    }
                }
        
            };
        })();
    //}
//}

/** Main Scenes **/
//{
    var menu = (function(){
        var anim = [-600, 600, -300];
        var buttons = [
            new Button(900, 270, 200, 100, "Play"),
            new Button(900, 390, 200, 100, "How"),
            new Button(900, 510, 200, 100, "Scores")
        ];
        var triggered = [false, false, false];
        return function(){
            background(255);
            image(bkgd, anim[0], 0);
            image(mountains, 0, anim[1]);
            fill(255);
            textFont(fbi, 100);
            text("ZENITH", 300, anim[2] - 20);
            for (var i = 0;i<buttons.length;i++){
                buttons[i].pack();
                buttons[i].x = lerp(buttons[i].x, 300, 0.1);
            }
            if (buttons[0].triggered){
                triggered[0] = true;
            }
            if (buttons[1].triggered){
                triggered[1] = true;
            }
            if (buttons[2].triggered){
                triggered[2] = true;
            }
            if (!triggered[0] && !triggered[1] && !triggered[2]){
                anim[0] = lerp(anim[0], 0, 0.1);
                anim[2] = lerp(anim[2], 150, 0.1);
                anim[1] = lerp(anim[1], 50, 0.1);
            }
            else {
                anim[0] = lerp(anim[0], -600, 0.1);
                anim[1] = lerp(anim[1], 600, 0.1);
                anim[2] = lerp(anim[2], -300, 0.1);
                for (var i = 0;i<buttons.length;i++){
                    buttons[i].pack();
                    buttons[i].x = lerp(buttons[i].x, 300, 0.1);
                }
            }
            if (anim[0] < -599){
                if (triggered[0]){
                    scene = "game";
                    triggered[0] = false;
                }
                if (triggered[1]){
                    scene = "how";
                    triggered[1] = false;
                }
                if (triggered[2]){
                    scene = "lead";
                    triggered[2] = false;
                }
            }
        };
    })();
    var logo = (function(){
        rectMode(CENTER);
        var pos = 0;
        var pos2 = 0;
        var fallspd = 0;
        var fT = 500;
        var lwY = 200;
        var lwVel = 0;
        var landed = false;
        var fY = 0;
        var trans = 0;
        return function() {
            noStroke();
            rectMode(CENTER);
            pushMatrix();
            scale(1.5);
            background(255);
            fill(73, 154, 155);
            rect(200, 200 + trans, 400, 400);
            fill(255);
            pushMatrix();
            translate(trans, fY);
            pushMatrix();
            translate(200, 200 + pos2);
            rotate(pos - 20);
            translate(-200, -200);
            rect(200, pos, 100, 100);
            rect(pos - 80, 200, 100, 100);
            rect(480 - pos, 200, 100, 100);
            popMatrix();
            textFont(fb, 40);
            if (pos > 199.9){
                text("littlewhinging", 200, lwY);
                fallspd += 0.5;
            }
            lwY += lwVel;
            text("x\nCorin Fist", 200, fT);
            popMatrix();
            pos = lerp(pos, 200, 0.1);
            pos2 += fallspd;
            if (pos2 > 600){
                fT = lerp(fT, 250, 0.1);
            }
            if (fT < 251){
                fT = 250;
                lwVel += 0.3;
                if (!landed){
                    lwVel = -10;
                }
                landed = true;
            }
            if (lwY > 180 && landed){
                lwY = 180;
                fY = lerp(fY, -20, 0.1);
            }
            if (fY < -19.999){
                trans = lerp(trans, 400, 0.1);
            }
            if (trans > 399.99){
                scene = "menu";
            }
            popMatrix();
        };
    })();
    createLevel();
    rectMode(CORNER);
    var game = (function(){
        var levelNum = maps.length;
        var xCam = 0;
        var yCam = 0;
        var hb = 300;
        var progress = 0;
        var trans = 0;
        var trans2 = 600;
        return function (){

            if (curLevel > 26){
                scene = "win";
            }
            pushMatrix();
            translate(random(-trans, trans) + trans2, random(-trans, trans) + trans2);
            if (curLevel < 20 || curLevel > 24){
                image(bkgd, 0, 0);
                image(mountains, 0, 0);
            }
            else {
                image(Cave, 0, 0);
            }
            pushMatrix();
            xCam = lerp(xCam, 300 - player.x-player.w/2, 0.06);
            yCam = lerp(yCam, 300 - player.y-player.w/2, 0.06);
            translate(xCam, yCam);
            for (var i = 0;i<block2s[curLevel].length;i++){
                block2s[curLevel][i].draw();
                block2s[curLevel][i].collide(player);
            }
            for (var i = 0;i<yetis[curLevel].length;i++){
                yetis[curLevel][i].draw();
                yetis[curLevel][i].moveX(player);
            }
            player.draw();
            player.moveX();
            for (var i = 0;i<blocks[curLevel].length;i++){
                blocks[curLevel][i].draw();
                blocks[curLevel][i].collideX(player);
                for (var y = 0;y<yetis[curLevel].length;y++){
                    blocks[curLevel][i].collideX(yetis[curLevel][y]);
                }
            }
            player.moveY();
            for (var i = 0;i<yetis[curLevel].length;i++){
                yetis[curLevel][i].moveY(player);
            }    
            for (var i = 0;i<blocks[curLevel].length;i++){
                blocks[curLevel][i].collideY(player);
                for (var y = 0;y<yetis[curLevel].length;y++){
                    blocks[curLevel][i].collideY(yetis[curLevel][y]);
                }
            }

            if (player.y > 2000 || player.health < 1){
                die(createLevel, false);
                trans = 255;
            }
            popMatrix();
            if (curLevel > 7){
                snowFall();
            }
            noStroke();
            fill(158, 0, 76);
            rect(150, 525, 300, 40);
            fill(0, 212, 141);
            rect(150, 525, hb, 40);
            hb = lerp(hb, player.health*3, 0.1);
            textFont(fb, 26);
            fill(0);
            text("Health: " + player.health, 300, 545);
            fill(0);
            textSize(30);
            text("Deaths: " + deaths, 500, 50);
            fill(189, 189, 189);
            rect(25, 150, 40, 300);
            fill(0, 212, 141);
            rect(25, 450 - progress, 40, progress);
            progress = lerp(progress, (curLevel+1) * 300/levelNum, 0.1);
            image(mountPeak, 15, 105, 100, 100);
            
            for (var i = 0;i<block2s[curLevel].length;i++){
                block2s[curLevel][i].drawSign();
            }
            if (typed[82]){
                die(createLevel, false);
            }
            popMatrix();
            fill(255, 0, 0, trans);
            rect(0, 0, 600, 600);
            trans = lerp(trans, 0, 0.1);
            trans2 = lerp(trans2, 0, 0.1);
        };
    })();
    var win = (function(){
        var trans = 0;
        var trans2 = 255;
        var trans3 = 0;
        return function() {
            if (trans > 30){
                image(bkgd, 0, 0);
                fill(81, 183, 185);
                noStroke();
                beginShape();
                vertex(-141, 600);
                vertex(600, 700);
                vertex(451, 290);
                vertex(300, 300);
                endShape(CLOSE);
                ellipse(319, 149, 50, 50);
                triangle(402, 155, 464, 171, 401, 193);
                stroke(81, 183, 185);
                strokeWeight(7);
                strokeCap(ROUND);
                line(307, 302, 320, 259);
                line(341, 302, 320, 259);
                line(320, 156, 320, 259);
                line(307, 224, 320, 176);
                line(333, 224, 320, 176);
                line(400, 300, 400, 150);
                stroke(255);
                strokeWeight(10);
                line(299, 128, 336, 128);
                fill(81, 183, 185);
                noStroke();
                beginShape();
                vertex(336, 123);
                bezierVertex(358, 115, 251, 59, 303, 123);
                endShape();
                fill(255);
                ellipse(292, 91, 20, 20);
                ellipse(400, 150, 20, 20);
                fill(255, trans2);
                rect(0, 0, 600, 600);
                trans2  = lerp(trans2, 0, 0.1);
            }
            else {
                fill(255, trans);
                noStroke();
                rect(0, 0, 600, 600);
            }
            trans += 0.3;
            if (trans2 < 0.0001){
                trans3 = lerp(trans3, 255, 0.1);
            }
            fill(255, trans3);
            rect(0, 0, 600, 600);
            if (trans3 > 254.999){
                scene = "win2";
            }
        };
    })();
    var win2 = (function(){
        var trans = 255;
        return function(){
            image(bkgd, 0, 0);
            image(mountains, 0, 0);
            textFont(fb, 50);
            fill(255);
            text("Congratulations", 300, 300);
            textSize(20);
            text("you finished with "+deaths+" deaths.", 300, 550);
            fill(255, trans);
            rect(0, 0, 600, 600);
            trans -- ;
        };
    })();
    var how = (function(){
        var pos = -600;
        var backBtn = new Button(300, 800, 200, 100, "back");
        var triggered = false;
        return function(){
            background(255);
            image(bkgd, pos, 0);
            image(mountains, 0 - pos, 0); 
            fill(255);
            textFont(fb, 100);
            text("HOW", 300, pos + 150);
            textSize(30);
            text("Move with the arrow keys,\nor WASD. The rest\nwill be explained in-game.", 300, pos + 300);
            backBtn.pack();
            if (backBtn.triggered){
                triggered = true;
            }
            if (triggered){
                pos = lerp(pos, -600, 0.1);
                backBtn.y = lerp(backBtn.y, 800, 0.1);
                if (backBtn.y > 799){
                    scene = "menu";
                    triggered = false;
                }
            }
            else {
                pos = lerp(pos, 0, 0.1);
                backBtn.y = lerp(backBtn.y, 500, 0.1);
            }
        };
    })();
    var lead = (function(){
        var pos = -600;
        var backBtn = new Button(300, 800, 200, 100, "back");
        var triggered = false;
        return function(){
            background(255);
            image(bkgd, pos, 0);
            image(mountains, 0 - pos, 0); 
            fill(255);
            textFont(fb, 70);
            text("LEADERBOARD", 300, pos + 75);
            textSize(30);
            for (var i = 0; i < leader.length; i++) {
                fill(250, 250, 250, 255 - i * 15);
                text( (i+1)+ ".  " + leader[i][0] + " :  " + leader[i][1], width / 2,pos+150 +i*40 );
            }
            backBtn.pack();
            if (backBtn.triggered){
                triggered = true;
            }
            if (triggered){
                pos = lerp(pos, -600, 0.1);
                backBtn.y = lerp(backBtn.y, 800, 0.1);
                if (backBtn.y > 799){
                    scene = "menu";
                    triggered = false;
                }
            }
            else {
                pos = lerp(pos, 0, 0.1);
                backBtn.y = lerp(backBtn.y, 500, 0.1);
            }
        };
    })();
//}

/** Processing.js functions **/
//{
    draw = function(){
        try {
            switch (scene) {
                case "logo":
                    logo();
                break;
                case "menu":
                    menu();
                break;
                case "game":
                    game();
                break;
                case "win":
                    win();
                break;
                case "win2":
                    win2();
                break;
                case "how":
                    how();
                break;
                case "lead":
                    lead();
            }
        }
        catch (e){
            println(e);
        }
        clicked[mouseButton] = false;
        typed[keyCode] = false;
    };
    mouseClicked = function(){
        clicked[mouseButton] = true;
    };
    keyPressed = function(){
        keys[keyCode] = true;
    };
    keyReleased = function(){
        keys[keyCode] = false;
        typed[keyCode] = true;
    };
//}
